title = "gerneral config file"

[database]
name = "work_times_MK.db"
path = "../database"

[create_table]
table_name = "times_2021"
create_command = "CREATE TABLE IF NOT EXISTS"
column_first = "date INTEGER PRIMARY KEY"
column_second = "login INTEGER"
column_third = "logout INTEGER"
column_fourth = "break INTEGER"
column_fifth = "work INTEGER"

