title = "gerneral config file"

[database]
name = "work_times_MK.db"
path = "../database"

[create_table]
table_name = "times_2021"
create_command = "CREATE TABLE IF NOT EXISTS"
column_first = "date"
column_second = "login"
column_third = "logout"
column_fourth = "break"
column_fifth = "work"
column_first_type = "TEXT PRIMARY KEY"
column_second_type = "TEXT"
column_third_type = "TEXT"
column_fourth_type = "TEXT"
column_fifth_type = "TEXT"
number_column = "5"

